apiVersion: v1
kind: Service
metadata:
  name: ms-gateway
  labels:
    app: ms-gateway
spec:
  type: NodePort
  selector:
    app: ms-gateway
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
      nodePort: 30092